.\" 
.\" Copyright (c) 1994 1995 1996 ... 2017 2018 
.\"     John McCue <jmccue@jmcunx.com>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

.TH j2_is_space_embedded 3 "$Date: 2018/07/02 23:06:16 $" "JMC" "Local Library Function"

.SH NAME
j2_is_space_embedded() - Check for embedded white space

.SH SYNOPSIS
#include <j_lib2.h>

int j2_is_space_embedded(char *s);

.SH DESCRIPTION
j2_is_space_embedded() determines if a string contains embedded white space.

White Space in the "C" and "POSIX" locales,
these are: space, form-feed ('\\f'), newline ('\\n'),
carriage return ('\\r'), horizontal tab ('\\t'),
and vertical tab ('\\v').

Please note, test will fail if the string contains leading white space.

The following strings will fail:
.nf
    "aa aa "
    "bb  bb"
    "   ccc"
.fi
The following strings will pass:
.nf
    "aaaaa "
    "bbbbbb"
    "cccc  "
.fi

.SH RETURN VALUES
TRUE or FALSE
