.\" 
.\" Copyright (c) 1994 1995 1996 ... 2017 2018 
.\"     John McCue <jmccue@jmcunx.com>
.\" 
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

.TH j2_is_numr 3 "$Date: 2018/03/07 01:40:04 $" "JMC" "Local Library Function"

.SH NAME
j2_is_numr() - Is the string numeric ?

.SH SYNOPSIS
.nf
#include <sys/types.h>
#include <j_lib2.h>

int j2_is_numr(char *s);
.fi

.SH DESCRIPTION
j2_is_numr() determines if a string contains 
all numeric characters.

.SH RETURNS
TRUE or FALSE

.SH DIAGNOSTICS
If the string contains any Decimal Points 
and/or Thousand Characters FALSE will be returned.

.SH SEE-ALSO
j_lib2(3)
